apiVersion: v1
kind: PersistentVolume
metadata:
  name: mainpv
spec:
  storageClassName: "local"
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /Users/shyamrai/Documents/projects/vagrant-k8s/pv

